AWSTemplateFormatVersion: 2010-09-09
Description: "S3 bucket with default encryption"
Resources:
  MakeshiftDemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'makeshift-demo-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete
Outputs:
  MakeshiftDemoBucketName:
    Description: "makeshift s3 demo bucket"
    Value: !Ref MakeshiftDemoBucket
    Export:
      Name: "MakeshiftDemoBucketName"
    
